name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    env:
      WINEPREFIX: ${{github.workspace}}/.wine
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout WiBo
      uses: actions/checkout@v3
      with:
        repository: decompals/WiBo
        path: tools/WiBo
    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential gcc-multilib g++-multilib libc6:i386
        curl -L https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip \
          | bsdtar -xvf- -C tools --exclude Wii
        mv tools/GC/* tools/mwcc_compiler/
    - name: Build WiBo
      working-directory: tools/WiBo
      run: |
        cmake -B build
        cmake --build build
    - name: Build
      run: make -j$(nproc) WINE=./tools/WiBo/build/wibo MAPGENFLAG=1
    - name: Upload map
      uses: actions/upload-artifact@v2
      with:
        name: pikmin2UP.MAP
        path: build/*/pikmin2UP.MAP
