name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/projectpiki/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [usa, usa.demo]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Build
      run: |
        python configure.py --map --version ${{matrix.version}} --compilers /compilers/GC
        ninja
    - name: Upload progress
      if: github.ref == 'refs/heads/main'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python tools/upload-progress.py -b https://progress.decomp.club/ -p pikmin2 -v ${{matrix.version}} \
          build/pikmin2.${{matrix.version}}/main.dol.progress
    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: pikmin2UP-${{matrix.version}}.MAP
        path: build/*/pikmin2UP.MAP

  build_make:
    name: Build (legacy)
    runs-on: ubuntu-latest
    container: ghcr.io/projectpiki/build:main
    strategy:
      fail-fast: false
      matrix:
        version: [usa, usa.demo]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Build
      run: make -j$(nproc) MAPGENFLAG=1 VERSION=${{matrix.version}} COMPILERS=/compilers/GC
